name: labelwise
description: A minimal LabelWise Flutter application.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  firebase_analytics: ^12.4.5
  firebase_core: ^4.12.1
  firebase_crashlytics: ^5.2.6
  flutter_dotenv: ^6.0.1
  http: ^1.6.0
  image_picker: ^1.2.3
  mobile_scanner: ^7.2.0
  shared_preferences: ^2.5.5
  supabase_flutter: ^2.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
