import 'package:flutter/foundation.dart';

class ProductCategoryMapper {
  const ProductCategoryMapper._();

  static const categories = <String>[
    'Cips',
    'Kraker',
    'Çikolata',
    'Bisküvi',
    'Şekerleme',
    'Kek & Tatlı',
    'Sütlü Tatlı',
    'Gazlı İçecek',
    'Meyve Suyu',
    'Soğuk Çay',
    'Enerji İçeceği',
    'Su & Maden Suyu',
    'Kahve',
    'Çay',
    'Süt',
    'Yoğurt & Fermente Süt',
    'Peynir',
    'Dondurma',
    'İşlenmiş Et',
    'Sos',
    'Sürülebilir Tatlı',
    'Yağ',
    'Tahıl & Bakliyat',
    'Ekmek & Unlu Mamul',
    'Hazır Yemek & Konserve',
    'Donuk Ürün',
    'Kuruyemiş',
    'Sporcu Ürünü',
    'Bebek Gıdası',
    'Baharat & Çeşni',
    'Diğer',
    'Belirsiz',
  ];

  static const _categoryAliases = <String, String>{
    'gofret': 'Bisküvi',
    'kek': 'Kek & Tatlı',
    'puding': 'Sütlü Tatlı',
    'maden suyu': 'Su & Maden Suyu',
    'su': 'Su & Maden Suyu',
    'yogurt': 'Yoğurt & Fermente Süt',
    'yogurt fermente sut': 'Yoğurt & Fermente Süt',
    'kahvaltilik gevrek': 'Tahıl & Bakliyat',
    'makarna': 'Tahıl & Bakliyat',
    'hazir corba': 'Hazır Yemek & Konserve',
    'konserve': 'Hazır Yemek & Konserve',
    'protein bar': 'Sporcu Ürünü',
    'diger': 'Diğer',
    'belirsiz': 'Belirsiz',
  };

  static const _strongNameRules = <_CategoryRule>[
    _CategoryRule('Soğuk Çay', [
      'lipton ice tea',
      'fuse tea',
      'fuzetea',
      'ice tea',
      'iced tea',
      'soğuk çay',
      'soguk cay',
      'didi',
    ]),
    _CategoryRule('İşlenmiş Et', [
      'tütsülenmiş piliç jumbo sosis',
      'tutsulenmis pilic jumbo sosis',
      'baton sucuk',
      'parmak sucuk',
      'kokteyl sosis',
      'piliç sosis',
      'pilic sosis',
      'dana sosis',
      'hindi salam',
      'hindi füme',
      'hindi fume',
      'tavuk füme',
      'tavuk fume',
      'dana füme',
      'dana fume',
    ]),
    _CategoryRule('Peynir', [
      'kaşar peyniri',
      'kasar peyniri',
      'eski kaşar',
      'eski kasar',
      'taze kaşar',
      'taze kasar',
      'süzme peynir',
      'suzme peynir',
      'beyaz peynir',
      'krem peynir',
      'dil peyniri',
      'örgü peynir',
      'orgu peynir',
      'üçgen peynir',
      'ucgen peynir',
      'pınar labne',
      'pinar labne',
      'sütaş peynir',
      'sutas peynir',
      'içim peynir',
      'icim peynir',
      'sek peynir',
      'torku peynir',
      'kiri',
    ]),
    _CategoryRule('Dondurma', [
      'sandviç dondurma',
      'sandvic dondurma',
      'maraş usulü',
      'maras usulu',
      'magnum',
      'cornetto',
      'algida',
      'nogger',
      "carte d'or",
      'carte dor',
      'max dondurma',
    ]),
    _CategoryRule('Kahve', [
      'türk kahvesi',
      'turk kahvesi',
      'filtre kahve',
      'hazır kahve',
      'hazir kahve',
      'soğuk kahve',
      'soguk kahve',
      'nescafe',
      'cappuccino',
      'latte',
      'espresso',
      '3ü1 arada',
      '3u1 arada',
      '3 1 arada',
      '2si1 arada',
      '2 si 1 arada',
    ]),
    _CategoryRule('Enerji İçeceği', [
      'red bull',
      'monster',
      'burn',
      'black bruin',
      'hell energy',
      'dark blue',
      'x-ir',
      'powerade',
    ]),
    _CategoryRule('Gazlı İçecek', [
      'coca cola',
      'coca-cola',
      'pepsi',
      'fanta',
      'sprite',
      'yedigün',
      'yedigun',
      'fruko',
      'uludağ gazoz',
      'uludag gazoz',
      'çamlıca gazoz',
      'camlica gazoz',
      'dr pepper',
    ]),
    _CategoryRule('Su & Maden Suyu', [
      'doğal kaynak suyu',
      'dogal kaynak suyu',
      'içme suyu',
      'icme suyu',
      'maden suyu',
      'doğal mineralli su',
      'dogal mineralli su',
      'mineralli su',
      'beypazarı',
      'beypazari',
      'kızılay soda',
      'kizilay soda',
      'kızılay maden suyu',
      'kizilay maden suyu',
      'sırma maden suyu',
      'sirma maden suyu',
      'uludağ maden suyu',
      'uludag maden suyu',
      'erikli',
      'hayat su',
    ]),
    _CategoryRule('Cips', [
      'patates cipsi',
      'mısır cipsi',
      'misir cipsi',
      'tortilla cips',
      'tortilla cipsi',
      'cipso',
      'ruffles',
      'lays',
      "lay's",
      'doritos',
      'pringles',
      'cheetos',
      'crunchips',
      'patos',
      'tadım cips',
      'tadim cips',
      'çerezza',
      'cerezza',
    ]),
    _CategoryRule('Kraker', [
      'çubuk kraker',
      'cubuk kraker',
      'eti crax',
      'crax',
      'çizi',
      'cizi',
      'tuc',
      'pretzel',
      'grissini',
    ]),
    _CategoryRule('Çikolata', [
      'sütlü çikolata',
      'sutlu cikolata',
      'bitter çikolata',
      'bitter cikolata',
      'beyaz çikolata',
      'beyaz cikolata',
      'kare çikolata',
      'kare cikolata',
      'bar çikolata',
      'bar cikolata',
      'ülker çikolata',
      'ulker cikolata',
      'eti karam',
      'milka',
      'nestle damak',
      'damak',
      'tadelle',
      'albeni',
      'metro',
      'hobby',
      'snickers',
      'mars',
      'twix',
      'kitkat',
      'kinder',
      'ferrero',
      'ülker napoliten',
      'ulker napoliten',
    ]),
    _CategoryRule('Bisküvi', [
      'kremalı bisküvi',
      'kremali biskuvi',
      'bebe bisküvisi',
      'bebe biskuvisi',
      'biskrem',
      'hanımeller',
      'hanimeller',
      'burçak',
      'burcak',
      'petit beurre',
      'petibör',
      'petibor',
      'potibör',
      'potibor',
      'oreo',
      'negro',
      'lotus',
      'tutku',
      'gofret',
      'wafer',
      'hoşbeş',
      'hosbes',
      'çokonat',
      'cokonat',
      '9 kat',
      'dokuz kat',
    ]),
    _CategoryRule('Kek & Tatlı', [
      'mozaik kek',
      'baton kek',
      'topkek',
      'popkek',
      'eti browni',
      'browni',
      'brownie',
      'olala',
      'dankek',
      'muffin',
      'profiterol',
      'ekler',
      'donut',
      'kruvasan',
      'croissant',
    ]),
    _CategoryRule('Sütlü Tatlı', [
      'danette',
      'daphne puding',
      'dr oetker puding',
      'sek puding',
      'içim puding',
      'icim puding',
      'sütlaç',
      'sutlac',
      'kazandibi',
      'tavuk göğsü',
      'tavuk gogsu',
      'supangle',
      'muhallebi',
      'keşkül',
      'keskul',
    ]),
    _CategoryRule('Sürülebilir Tatlı', [
      'fındık kreması',
      'findik kremasi',
      'kakaolu fındık kreması',
      'kakaolu findik kremasi',
      'fıstık ezmesi',
      'fistik ezmesi',
      'nutella',
      'sarelle',
      'çokokrem',
      'cokokrem',
      'torku banada',
    ]),
    _CategoryRule('Sos', [
      'barbekü sos',
      'barbeku sos',
      'acı sos',
      'aci sos',
      'soya sosu',
      'nar ekşisi',
      'nar eksisi',
      'salata sosu',
      'ketçap',
      'ketcap',
      'ketchup',
      'mayonez',
      'mayonnaise',
      'hardal',
      'ranch',
      'pesto',
    ]),
    _CategoryRule('Tahıl & Bakliyat', [
      'corn flakes',
      'kahvaltılık gevrek',
      'kahvaltilik gevrek',
      'mısır gevreği',
      'misir gevregi',
      'eti lifalif granola',
      "kellogg's",
      'kelloggs',
      'cheerios',
      'nuhun ankara',
      "nuh'un ankara",
      'barilla',
      'filiz makarna',
    ]),
    _CategoryRule('Hazır Yemek & Konserve', [
      'dardanel ton',
      'ton balığı',
      'ton baligi',
      'barbunya pilaki',
      'fasulye pilaki',
      'hazır yemek',
      'hazir yemek',
      'hazır çorba',
      'hazir corba',
      'knorr çorba',
      'knorr corba',
      'knorr mercimek çorbası',
      'knorr mercimek corbasi',
      'bizim mutfak çorba',
      'bizim mutfak corba',
      'yayla hazır çorba',
      'yayla hazir corba',
      'indomie',
      'nissin noodle',
    ]),
    _CategoryRule('Donuk Ürün', [
      'dondurulmuş pizza',
      'dondurulmus pizza',
      'dondurulmuş mantı',
      'dondurulmus manti',
      'dondurulmuş sebze',
      'dondurulmus sebze',
      'patates kızartması',
      'patates kizartmasi',
      'superfresh',
    ]),
    _CategoryRule('Sporcu Ürünü', [
      'protein bar',
      'protein barı',
      'protein bari',
      'whey protein',
      'protein tozu',
      'supplement bar',
      'züber protein',
      'zuber protein',
      'be kind protein',
      'protein ocean bar',
      'weider protein bar',
      'bcaa',
      'kreatin',
      'creatine',
    ]),
    _CategoryRule('Bebek Gıdası', [
      'bebek maması',
      'bebek mamasi',
      'devam sütü',
      'devam sutu',
      'kaşık maması',
      'kasik mamasi',
      'kavanoz maması',
      'kavanoz mamasi',
      'çocuk sütü',
      'cocuk sutu',
    ]),
  ];

  static const _generalRules = <_CategoryRule>[
    _CategoryRule('Soğuk Çay', [
      'ice tea',
      'iced tea',
      'soğuk çay',
      'soguk cay',
      'fuse tea',
      'fuzetea',
      'lipton ice tea',
      'didi',
    ]),
    _CategoryRule('İşlenmiş Et', [
      'sucuk',
      'salam',
      'sosis',
      'pastırma',
      'pastirma',
      'kavurma',
      'jambon',
      'füme',
      'fume',
      'işlenmiş et',
      'islenmis et',
    ]),
    _CategoryRule('Peynir', [
      'cheese',
      'peynir',
      'beyaz peynir',
      'kaşar',
      'kasar',
      'süzme peynir',
      'suzme peynir',
      'labne',
      'krem peynir',
      'lor',
      'çökelek',
      'cokelek',
      'tulum',
      'hellim',
      'mihaliç',
      'mihalic',
      'dil peyniri',
      'örgü peynir',
      'orgu peynir',
      'üçgen peynir',
      'ucgen peynir',
    ]),
    _CategoryRule('Dondurma', [
      'ice cream',
      'icecream',
      'dondurma',
      'gelato',
      'külah',
      'kulah',
      'sandviç dondurma',
      'sandvic dondurma',
      'maraş usulü',
      'maras usulu',
    ]),
    _CategoryRule('Enerji İçeceği', [
      'energy drink',
      'energy drinks',
      'enerji içeceği',
      'enerji icecegi',
    ]),
    _CategoryRule('Gazlı İçecek', [
      'soft drinks',
      'soft drink',
      'carbonated drinks',
      'carbonated drink',
      'gazlı içecek',
      'gazli icecek',
      'cola',
      'kola',
      'gazoz',
    ]),
    _CategoryRule('Kahve', [
      'coffee',
      'kahve',
      'türk kahvesi',
      'turk kahvesi',
      'filtre kahve',
      'espresso',
      'hazır kahve',
      'hazir kahve',
      'cappuccino',
      'latte',
      'soğuk kahve',
      'soguk kahve',
    ]),
    _CategoryRule('Çay', [
      'siyah çay',
      'siyah cay',
      'yeşil çay',
      'yesil cay',
      'bitki çayı',
      'bitki cayi',
      'adaçayı',
      'adacayi',
      'ıhlamur',
      'ihlamur',
      'rezene',
      'kuşburnu',
      'kusburnu',
      'lipton çay',
      'lipton cay',
      'doğuş çay',
      'dogus cay',
      'çaykur',
      'caykur',
      'tea',
      'çay',
      'cay',
    ]),
    _CategoryRule('Su & Maden Suyu', [
      'still water',
      'spring water',
      'mineral water',
      'sparkling water',
      'carbonated water',
      'doğal kaynak suyu',
      'dogal kaynak suyu',
      'içme suyu',
      'icme suyu',
      'maden suyu',
      'soda',
      'mineralli su',
      'aromalı maden suyu',
      'aromali maden suyu',
      'meyveli soda',
      'water',
      'su',
    ]),
    _CategoryRule('Cips', [
      'potato crisps',
      'potato chips',
      'patates cipsi',
      'mısır cipsi',
      'misir cipsi',
      'tortilla cips',
      'tortilla cipsi',
      'nachos',
      'nacho',
      'taco chips',
      'nacho chips',
      'crisps',
      'chips',
      'cips',
    ]),
    _CategoryRule('Kraker', [
      'crackers',
      'cracker',
      'kraker',
      'çubuk kraker',
      'cubuk kraker',
      'breadsticks',
      'pretzel',
      'pretzels',
      'galeta',
      'grissini',
      'çıtır',
      'citir',
    ]),
    _CategoryRule('Çikolata', [
      'chocolates',
      'chocolate',
      'çikolata',
      'cikolata',
      'sütlü çikolata',
      'sutlu cikolata',
      'bitter',
      'beyaz çikolata',
      'beyaz cikolata',
      'napoliten',
      'tablet çikolata',
      'tablet cikolata',
      'bar çikolata',
      'bar cikolata',
    ]),
    _CategoryRule('Şekerleme', [
      'şekerleme',
      'sekerleme',
      'jelibon',
      'lokum',
      'sakız',
      'sakiz',
      'candy',
      'bonibon',
      'draje',
      'marshmallow',
      'lolipop',
    ]),
    _CategoryRule('Bebek Gıdası', [
      'bebek maması',
      'bebek mamasi',
      'mama',
      'devam sütü',
      'devam sutu',
      'kaşık maması',
      'kasik mamasi',
      'bebek bisküvisi',
      'bebek biskuvisi',
      'kavanoz maması',
      'kavanoz mamasi',
      'çocuk sütü',
      'cocuk sutu',
    ]),
    _CategoryRule('Bisküvi', [
      'biscuits',
      'biscuit',
      'biscotti',
      'cookies',
      'cookie',
      'bisküvi',
      'biskuvi',
      'kremalı bisküvi',
      'kremali biskuvi',
      'sandviç bisküvi',
      'sandvic biskuvi',
      'kakaolu bisküvi',
      'kakaolu biskuvi',
      'yulaflı bisküvi',
      'yulafli biskuvi',
      'gofret',
      'wafer',
    ]),
    _CategoryRule('Kek & Tatlı', [
      'cakes',
      'cake',
      'kek',
      'muffin',
      'brownie',
      'sufle',
      'suffle',
      'mini kek',
      'pasta',
      'profiterol',
      'ekler',
      'donut',
      'kruvasan',
      'croissant',
    ]),
    _CategoryRule('Sütlü Tatlı', [
      'puding',
      'pudding',
      'dessert',
      'desserts',
      'custard',
      'muhallebi',
      'supangle',
      'kazandibi',
      'sütlaç',
      'sutlac',
      'tavuk göğsü',
      'tavuk gogsu',
      'keşkül',
      'keskul',
    ]),
    _CategoryRule('Meyve Suyu', [
      'fruit juices',
      'fruit juice',
      'juice',
      'meyve suyu',
      'nektar',
      'nectar',
      'meyveli içecek',
      'meyveli icecek',
      'portakal suyu',
      'vişne suyu',
      'visne suyu',
      'elma suyu',
      'şeftali suyu',
      'seftali suyu',
      'kayısı suyu',
      'kayisi suyu',
      'aromalı içecek',
      'aromali icecek',
      'içecek',
      'icecek',
    ]),
    _CategoryRule('Yoğurt & Fermente Süt', [
      'yogurt',
      'yoghurt',
      'yoğurt',
      'yogurt',
      'strained yogurt',
      'süzme yoğurt',
      'suzme yogurt',
      'probiyotik yoğurt',
      'probiyotik yogurt',
      'ayran',
      'kefir',
      'cacık',
      'cacik',
    ]),
    _CategoryRule('Süt', [
      'uht milk',
      'whole milk',
      'semi skimmed milk',
      'skimmed milk',
      'tam yağlı süt',
      'tam yagli sut',
      'yarım yağlı süt',
      'yarim yagli sut',
      'laktozsuz süt',
      'laktozsuz sut',
      'günlük süt',
      'gunluk sut',
      'pastörize süt',
      'pastorize sut',
      'milk',
      'süt',
      'sut',
    ]),
    _CategoryRule('Sos', [
      'sauces',
      'sauce',
      'ketçap',
      'ketcap',
      'ketchup',
      'mayonez',
      'mayonnaise',
      'hardal',
      'mustard',
      'barbekü sos',
      'barbeku sos',
      'bbq sauce',
      'acı sos',
      'aci sos',
      'hot sauce',
      'ranch',
      'pesto',
      'soya sosu',
      'nar ekşisi',
      'nar eksisi',
      'salata sosu',
      'salça',
      'salca',
      'sos',
    ]),
    _CategoryRule('Sürülebilir Tatlı', [
      'reçel',
      'recel',
      'jam',
      'bal',
      'honey',
      'pekmez',
      'fındık kreması',
      'findik kremasi',
      'chocolate spread',
      'hazelnut spread',
      'nutella',
      'sarelle',
      'torku banada',
      'ezme',
      'fıstık ezmesi',
      'fistik ezmesi',
      'tahin',
    ]),
    _CategoryRule('Yağ', [
      'zeytinyağı',
      'zeytinyagi',
      'ayçiçek yağı',
      'aycicek yagi',
      'sıvı yağ',
      'sivi yag',
      'tereyağı',
      'tereyagi',
      'margarin',
      'mısır yağı',
      'misir yagi',
      'kanola yağı',
      'kanola yagi',
      'fındık yağı',
      'findik yagi',
    ]),
    _CategoryRule('Tahıl & Bakliyat', [
      'pirinç',
      'pirinc',
      'bulgur',
      'mercimek',
      'nohut',
      'fasulye',
      'barbunya',
      'makarna',
      'spaghetti',
      'spagetti',
      'erişte',
      'eriste',
      'şehriye',
      'sehriye',
      'kuskus',
      'yulaf',
      'granola',
      'müsli',
      'musli',
      'corn flakes',
      'gevrek',
      'cereal',
    ]),
    _CategoryRule('Ekmek & Unlu Mamul', [
      'tost ekmeği',
      'tost ekmegi',
      'sandviç ekmeği',
      'sandvic ekmegi',
      'lavaş',
      'lavas',
      'tortilla',
      'bazlama',
      'yufka',
      'galeta unu',
      'ekmek',
      'un',
    ]),
    _CategoryRule('Donuk Ürün', [
      'dondurulmuş',
      'dondurulmus',
      'donuk',
      'frozen',
      'patates kızartması',
      'patates kizartmasi',
      'dondurulmuş pizza',
      'dondurulmus pizza',
      'dondurulmuş mantı',
      'dondurulmus manti',
      'dondurulmuş sebze',
      'dondurulmus sebze',
      'superfresh',
    ]),
    _CategoryRule('Hazır Yemek & Konserve', [
      'canned food',
      'canned',
      'konserve',
      'ton balığı',
      'ton baligi',
      'tuna',
      'dardanel',
      'barbunya pilaki',
      'fasulye pilaki',
      'hazır yemek',
      'hazir yemek',
      'çorba',
      'corba',
      'hazır çorba',
      'hazir corba',
      'noodle',
      'ramen',
      'mantı',
      'manti',
      'pizza',
      'nugget',
      'schnitzel',
      'döner',
      'doner',
      'köfte',
      'kofte',
    ]),
    _CategoryRule('Kuruyemiş', [
      'kuruyemiş',
      'kuruyemis',
      'fındık',
      'findik',
      'fıstık',
      'fistik',
      'badem',
      'ceviz',
      'kaju',
      'antep fıstığı',
      'antep fistigi',
      'leblebi',
      'çekirdek',
      'cekirdek',
      'kuru üzüm',
      'kuru uzum',
      'kuru kayısı',
      'kuru kayisi',
      'kuru incir',
      'hurma',
    ]),
    _CategoryRule('Sporcu Ürünü', [
      'protein bar',
      'protein',
      'whey',
      'protein tozu',
      'sporcu',
      'bcaa',
      'kreatin',
      'creatine',
      'supplement bar',
    ]),
    _CategoryRule('Baharat & Çeşni', [
      'karabiber',
      'pul biber',
      'kimyon',
      'nane',
      'kekik',
      'bulyon',
      'et suyu',
      'tavuk suyu',
      'çeşni',
      'cesni',
      'baharat',
      'tuz',
    ]),
    _CategoryRule('Şekerleme', ['şeker', 'seker']),
  ];

  static String normalizeCategory(String? value) {
    return (value ?? '')
        .replaceAll('İ', 'I')
        .replaceAll('Ç', 'C')
        .replaceAll('Ğ', 'G')
        .replaceAll('Ö', 'O')
        .replaceAll('Ş', 'S')
        .replaceAll('Ü', 'U')
        .toLowerCase()
        .replaceAll('ç', 'c')
        .replaceAll('ğ', 'g')
        .replaceAll('ı', 'i')
        .replaceAll('ö', 'o')
        .replaceAll('ş', 's')
        .replaceAll('ü', 'u')
        .replaceAll('&', ' ')
        .replaceAll(RegExp(r'\s+'), ' ')
        .trim();
  }

  static String? canonicalCategory(String? value) {
    final normalized = normalizeCategory(value);
    if (normalized.isEmpty) return null;

    for (final category in categories) {
      if (normalizeCategory(category) == normalized) return category;
    }
    return _categoryAliases[normalized] ?? value?.trim();
  }

  static String inferCategory({
    String? productName,
    String? brand,
    String? ingredientsText,
    List<String>? categoriesTags,
    String? categoriesText,
  }) {
    final nameText = [productName, brand].whereType<String>().join(' ');
    final normalizedName = _normalize(nameText);
    debugPrint(
      'CategoryMapper: product name=${productName ?? ''} '
      'normalized text=$normalizedName',
    );

    final strongNameMatch = _classifyStrongName(nameText);
    if (strongNameMatch != null) {
      _logResult(strongNameMatch, 'strong_name');
      return strongNameMatch.category;
    }

    final offCategoryText = [
      ...?categoriesTags,
      if (categoriesText != null) categoriesText,
    ].join(' ');
    final offCategoryMatch = _classify(offCategoryText);
    if (offCategoryMatch != null) {
      _logResult(offCategoryMatch, 'off_tags');
      return offCategoryMatch.category;
    }

    final nameCategoryMatch = _classify(nameText, sodaMeansMineralWater: true);
    if (nameCategoryMatch != null) {
      _logResult(nameCategoryMatch, 'name');
      return nameCategoryMatch.category;
    }

    final hasAnyInput = [
      offCategoryText,
      nameText,
      ingredientsText ?? '',
    ].any((value) => value.trim().isNotEmpty);
    final fallback = hasAnyInput ? 'Diğer' : 'Belirsiz';
    debugPrint(
      'CategoryMapper: matched keyword=none category=$fallback source=fallback',
    );
    return fallback;
  }

  static _CategoryMatch? _classifyStrongName(String value) {
    final text = _normalize(value);
    if (text.isEmpty) return null;

    for (final rule in _strongNameRules) {
      final keyword = _matchedKeyword(text, rule.keywords);
      if (keyword != null) return _CategoryMatch(rule.category, keyword);
    }
    if (_matchedKeyword(text, const ['schweppes']) != null &&
        _matchedKeyword(text, const ['tonic', 'mineral', 'maden suyu']) ==
            null) {
      return const _CategoryMatch('Gazlı İçecek', 'schweppes');
    }
    return null;
  }

  static _CategoryMatch? _classify(
    String value, {
    bool sodaMeansMineralWater = false,
  }) {
    final text = _normalize(value);
    if (text.isEmpty) return null;
    if (sodaMeansMineralWater) {
      final sodaKeyword = _matchedKeyword(text, const ['soda']);
      if (sodaKeyword != null) {
        return _CategoryMatch('Su & Maden Suyu', sodaKeyword);
      }
    }
    for (final rule in _generalRules) {
      final keyword = _matchedKeyword(text, rule.keywords);
      if (keyword != null) return _CategoryMatch(rule.category, keyword);
    }
    return null;
  }

  static String? _matchedKeyword(String normalizedText, List<String> keywords) {
    final paddedText = ' $normalizedText ';
    for (final keyword in keywords) {
      final normalizedKeyword = _normalize(keyword);
      if (paddedText.contains(' $normalizedKeyword ')) return keyword;
    }
    return null;
  }

  static String _normalize(String value) {
    return normalizeCategory(value)
        .replaceAll(RegExp(r'[^a-z0-9]+'), ' ')
        .replaceAll(RegExp(r'\s+'), ' ')
        .trim();
  }

  static void _logResult(_CategoryMatch match, String source) {
    debugPrint(
      'CategoryMapper: matched keyword=${match.keyword} '
      'category=${match.category} source=$source',
    );
  }
}

class _CategoryRule {
  const _CategoryRule(this.category, this.keywords);

  final String category;
  final List<String> keywords;
}

class _CategoryMatch {
  const _CategoryMatch(this.category, this.keyword);

  final String category;
  final String keyword;
}
